### ISSUE TITLE
Koodikatselmointi vk3

### ISSUE THREAD

**Issue by w4ldo** [linili/Tsoha-Bootstrap#1]
ke 7.6 klo 17.25

Kattava dokumentaatio koitin löytää jotain huomiota mutta hyvältä näyttää!

Esittelyssä käyttäjä voi kirjautumisen jälkeen luoda äänestyksen mutta käyttötapauksissa se listataan vain ylläpitäjän oikeudeksi

Tietokantakaaviossa Ääni viittaa Ehdokkaaseen, Pelaajaan ja Äänestyksen mutta Ehdokkaalla ei ole yksilöivää tunnistetta. Tarkemmalla silmäilyllä create_tables.sql näyttää että Ehdokkalta löytyy PK ja siihen viitataan mutta äänestykseen ei ole viitata.

Osa readmessa listatuista näkymistä antaa 404/fatalerror

Uuden äänestyksen luomisessa Käynnissä/Ei vielä alkanut voisi korvata esim checkboxilla ja ylläpitäjä voisi olla oletusarvoisesti äänestyksen luoja.

**Comment by linili** [comment]
Kiitos hyvistä huomioista! :)
